export const generosList = [
  "Trap",
  "HipHop",
  "RKT",
  "Cumbia",
  "Reggaeton",
  "Drill",
  "Pop",
  "Electronica",
  "Funk",
  "Rock",
  "R&B",
  "Cristiana",
  "Country",
  "Jazz",
  "Acustica",
  "Kpop",
  "Afrobeat",
  "Dembow",
  "Mambo",
  "Lo Fi",
  "Reggae",
  "Videojuegos",
  "Tango",
  "Zamba",
  "Folklore argentino",
  "Rock argentino",
  "Cuarteto",
  "Mariachi",
  "Ranchera",
  "Norteño",
  "Banda",
  "Cumbia mexicana",
  "Corrido",
  "Huapango",
  "Son cubano",
  "Cha-cha-cha",
  "Bolero",
  "Timba",
  "Rumba",
  "Salsa",
  "Plena",
  "Merengue",
  "Bachata",
  "Vallenato",
  "Champeta",
  "Salsa choke",
  "Joropo",
  "Gaita",
  "Salsa venezolana",
  "Samba",
  "Bossa Nova",
  "Forró",
  "Axé",
  "MPB (Música Popular Brasileña)",
  "Funk carioca",
  "Cueca",
  "Nueva Canción Chilena",
  "Folklore chileno",
  "Cumbia chilena",
  "Marinera",
  "Huayno",
  "Saya",
  "Festejo",
  "Cumbia peruana",
  "Pasillo",
  "Sanjuanito",
  "Bomba",
  "Chicha",
  "Caporales",
  "Morenada",
  "Tinku",
  "Huayño",
  "Candombe",
  "Murga",
  "Milonga",
  "Tango uruguayo",
  "Guarania",
  "Polca paraguaya",
  "Jopara",
  "Marimba",
  "Sonidero",
  "Garifuna",
  "Punta",
  "Cumbia salvadoreña",
  "Ska salvadoreño",
  "Palo de Mayo",
  "Mestizaje musical",
  "Punto guanacasteco",
  "Cumbia costarricense",
  "Salsa panameña",
  "Reggae en español",
  "Trova",
];
